# dl_ch4_2081_ashwin.py
# Chapter 4: 2081 Ashwin Examination Master Solutions

def get_chapter_2081_ashwin():
    return r"""
\chapter{2081 Ashwin Examination Solutions}

\section*{Examination Overview}
\begin{tabular}{@{}ll@{}}
\textbf{Level:} Bachelor in Engineering (BE) & \textbf{Full Marks:} 60 \\
\textbf{Programme:} BEI, BCT & \textbf{Pass Marks:} 24 \\
\textbf{Year / Part:} I / II & \textbf{Time:} 3 Hours \\
\textbf{Subject:} Digital Logic (ENEX 152) & \textbf{Examination Type:} Regular (New Course - 2080 Batch) \\
\end{tabular}

\vspace{0.6cm}
\hrule
\vspace{0.6cm}

% =========================================================================
% QUESTION 1
% =========================================================================
\subsection{Question 1: Merits \& Demerits of Digital Signals [2 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q1)}
Mention merits and demerits of digital signal over analog signal.
\end{questionbox}

\paragraph{Merits of Digital Signals:}
\begin{enumerate}
  \item \textbf{Superior Noise Immunity:} Digital circuits distinguish only discrete voltage bands (`0' and `1'). As long as noise voltage does not exceed the logic threshold, signal integrity is perfectly regenerated by repeaters.
  \item \textbf{Lossless Storage and Reproduction:} Data stored in semiconductor memory or optical media can be retrieved and duplicated indefinitely without analog degradation.
  \item \textbf{Advanced Error Detection and Correction:} Robust mathematical codes (Parity, CRC, Hamming, Reed-Solomon) can detect and correct bit errors caused during transmission.
  \item \textbf{Programmability and Integration:} Standard digital VLSI architectures (FPGA, DSP, Microprocessors) allow flexible software reconfigurability and massive circuit density.
\end{enumerate}

\paragraph{Demerits of Digital Signals:}
\begin{enumerate}
  \item \textbf{Higher Bandwidth Requirement:} Transmitting digital square pulses requires significantly wider channel bandwidth than transmitting the raw baseband analog waveform.
  \item \textbf{Quantization Error:} Analog-to-Digital Conversion (ADC) introduces unavoidable quantization noise due to finite bit resolution.
  \item \textbf{System Complexity:} Requires ADC and DAC conversion stages at real-world physical interfaces.
\end{enumerate}

\begin{answerbox}
Digital signals provide unmatched noise immunity, lossless storage, and error correction at the expense of higher transmission bandwidth and quantization artifacts.
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 2
% =========================================================================
\subsection{Question 2: Radix \& Gray Code Conversions [1.5 + 1.5 = 3 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q2)}
Perform the following as indicated:
\begin{enumerate}[label=(\alph*)]
  \item $(6E.2C)_{16} = (?)_{8}$
  \item $(10110110)_{\text{Gray}} = (?)_{2}$
\end{enumerate}
\end{questionbox}

\paragraph{Part (a): Hexadecimal to Octal Conversion: $(6E.2C)_{16} \to (?)_{8}$ [1.5 Marks]}
\begin{enumerate}
  \item \textbf{Convert Hexadecimal to 4-bit Binary:}
  \[
  6_{16} = 0110_2, \quad E_{16} = 1110_2, \quad 2_{16} = 0010_2, \quad C_{16} = 1100_2
  \]
  \[
  (6E.2C)_{16} = (0110\ 1110\ .\ 0010\ 1100)_2
  \]
  \item \textbf{Regroup into 3-bit Octal Groups:}
  \begin{itemize}
    \item \textbf{Integer part (grouping leftward from radix point):}
    \[
    \underbrace{001}_{1}\ \underbrace{101}_{5}\ \underbrace{110}_{6} \implies (156)_8
    \]
    \item \textbf{Fractional part (grouping rightward from radix point):}
    \[
    \underbrace{001}_{1}\ \underbrace{011}_{3}\ \underbrace{000}_{0} \implies (.130)_8 = (.13)_8
    \]
  \end{itemize}
\end{enumerate}
Thus, $(6E.2C)_{16} = \mathbf{(156.13)_8}$.

\paragraph{Part (b): Gray Code to Binary Conversion: $(10110110)_{\text{Gray}} \to (?)_{2}$ [1.5 Marks]}
Given $g_7 g_6 g_5 g_4 g_3 g_2 g_1 g_0 = 10110110_2$:
\begin{itemize}
  \item $b_7 = g_7 = 1$
  \item $b_6 = b_7 \oplus g_6 = 1 \oplus 0 = 1$
  \item $b_5 = b_6 \oplus g_5 = 1 \oplus 1 = 0$
  \item $b_4 = b_5 \oplus g_4 = 0 \oplus 1 = 1$
  \item $b_3 = b_4 \oplus g_3 = 1 \oplus 0 = 1$
  \item $b_2 = b_3 \oplus g_2 = 1 \oplus 1 = 0$
  \item $b_1 = b_2 \oplus g_1 = 0 \oplus 1 = 1$
  \item $b_0 = b_1 \oplus g_0 = 1 \oplus 0 = 1$
\end{itemize}
Thus, $(10110110)_{\text{Gray}} = \mathbf{(11011011)_2}$.

\begin{answerbox}
\begin{align*}
\text{(a)}\quad (6E.2C)_{16} &= \mathbf{(156.13)_8} \\
\text{(b)}\quad (10110110)_{\text{Gray}} &= \mathbf{(11011011)_2}
\end{align*}
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 3
% =========================================================================
\subsection{Question 3: BCD to 7-Segment 'f' Segment Decoder Logic Circuit [4 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q3)}
Design the simplest logic circuit for `$f$' segment for the BCD-to-seven segment display decoder.
\end{questionbox}

A 7-segment display uses LED segments $a, b, c, d, e, f, g$. The `$f$' segment represents the upper-left vertical LED segment, which must be illuminated (HIGH) for decimal digits \textbf{0, 4, 5, 6, 8, 9}.

\paragraph{1. Truth Table for Segment $f(A, B, C, D)$ (where $A$ is MSB):}
\begin{center}
\small
\begin{tabular}{|c|cccc||c|l|}
\hline
\textbf{Decimal Digit} & $A$ & $B$ & $C$ & $D$ & $\mathbf{f}$ & \textbf{Display Appearance} \\ \hline
0 & 0 & 0 & 0 & 0 & \textbf{1} & Illuminated \\ \hline
1 & 0 & 0 & 0 & 1 & \textbf{0} & Off \\ \hline
2 & 0 & 0 & 1 & 0 & \textbf{0} & Off \\ \hline
3 & 0 & 0 & 1 & 1 & \textbf{0} & Off \\ \hline
4 & 0 & 1 & 0 & 0 & \textbf{1} & Illuminated \\ \hline
5 & 0 & 1 & 0 & 1 & \textbf{1} & Illuminated \\ \hline
6 & 0 & 1 & 1 & 0 & \textbf{1} & Illuminated \\ \hline
7 & 0 & 1 & 1 & 1 & \textbf{0} & Off \\ \hline
8 & 1 & 0 & 0 & 0 & \textbf{1} & Illuminated \\ \hline
9 & 1 & 0 & 0 & 1 & \textbf{1} & Illuminated \\ \hline
10--15 & \multicolumn{4}{c||}{\text{Invalid BCD Codes}} & $\mathbf{X}$ & Don't Cares ($d_{10} \dots d_{15}$) \\ \hline
\end{tabular}
\end{center}

\paragraph{2. 4-Variable K-Map Minimization:}
\begin{center}
\begin{tabular}{|c|c|c|c|c|}
\hline
$AB \ \backslash \ CD$ & \textbf{00} & \textbf{01} & \textbf{11} & \textbf{10} \\ \hline
\textbf{00} & $\mathbf{1}\ (m_0)$ & $0\ (m_1)$ & $0\ (m_3)$ & $0\ (m_2)$ \\ \hline
\textbf{01} & $\mathbf{1}\ (m_4)$ & $\mathbf{1}\ (m_5)$ & $0\ (m_7)$ & $\mathbf{1}\ (m_6)$ \\ \hline
\textbf{11} & $\mathbf{X}\ (d_{12})$ & $\mathbf{X}\ (d_{13})$ & $\mathbf{X}\ (d_{15})$ & $\mathbf{X}\ (d_{14})$ \\ \hline
\textbf{10} & $\mathbf{1}\ (m_8)$ & $\mathbf{1}\ (m_9)$ & $\mathbf{X}\ (d_{11})$ & $\mathbf{X}\ (d_{10})$ \\ \hline
\end{tabular}
\end{center}

\paragraph{Groupings:}
\begin{enumerate}
  \item \textbf{Group 1 (Octet in rows 11 \& 10):} $(m_8, m_9, d_{10}, d_{11}, d_{12}, d_{13}, d_{14}, d_{15}) \implies \mathbf{A}$.
  \item \textbf{Group 2 (Quad in columns 00 \& 01, rows 01 \& 11):} $(m_4, m_5, d_{12}, d_{13}) \implies \mathbf{B\bar{C}}$.
  \item \textbf{Group 3 (Quad in column 00):} $(m_0, m_4, d_{12}, m_8) \implies \mathbf{\bar{C}\bar{D}}$.
  \item \textbf{Group 4 (Quad across rows 01 \& 11, cols 00 \& 10):} $(m_4, m_6, d_{12}, d_{14}) \implies \mathbf{B\bar{D}}$.
\end{enumerate}

\paragraph{Minimal Boolean Expression:}
\[
\mathbf{f = A + B\bar{C} + B\bar{D} + \bar{C}\bar{D}}
\]

\begin{schematicbox}{Logic Circuit Realization for Segment 'f'}
\centering
\begin{tikzpicture}[scale=0.92, transform shape]
  % 3 AND Gates
  \node[and gate US, draw, logic gate inputs=nn] (and1) at (3.5, 3.2) {};
  \node[and gate US, draw, logic gate inputs=nn] (and2) at (3.5, 1.8) {};
  \node[and gate US, draw, logic gate inputs=nn] (and3) at (3.5, 0.4) {};

  % Inputs
  \draw[thick] (1.0, 3.45) node[left] {$B$} -- (and1.input 1);
  \draw[thick] (1.0, 2.95) node[left] {$\bar{C}$} -- (and1.input 2);

  \draw[thick] (1.0, 2.05) node[left] {$B$} -- (and2.input 1);
  \draw[thick] (1.0, 1.55) node[left] {$\bar{D}$} -- (and2.input 2);

  \draw[thick] (1.0, 0.65) node[left] {$\bar{C}$} -- (and3.input 1);
  \draw[thick] (1.0, 0.15) node[left] {$\bar{D}$} -- (and3.input 2);

  % 4-input OR gate
  \node[or gate US, draw, logic gate inputs=nnnn, scale=1.2] (orgate) at (7.5, 2.2) {};
  \draw[thick] (1.0, 4.4) node[left] {$A$} -- (5.5, 4.4) |- (orgate.input 1);
  \draw[thick] (and1.output) -- ++(1.0, 0) |- (orgate.input 2);
  \draw[thick] (and2.output) -- ++(1.0, 0) |- (orgate.input 3);
  \draw[thick] (and3.output) -- ++(1.5, 0) |- (orgate.input 4);

  \draw[thick] (orgate.output) -- ++(1.0, 0) node[right] {\large $\mathbf{f}$};
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
$$\mathbf{f = A + B\bar{C} + B\bar{D} + \bar{C}\bar{D}}$$
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 4
% =========================================================================
\subsection{Question 4: 4:1 MUX Realization \& Combined Adder/Subtractor [3 + 7 = 10 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q4)}
Implement $Y(A, B, C) = \sum m(0, 2, 3, 5, 7)$ using only a single $4:1$ MUX. Design a circuit which can realize both the half-adder and the half-subtractor in a single circuit.
\end{questionbox}

\paragraph{Part (a): Realize $Y(A, B, C) = \sum m(0, 2, 3, 5, 7)$ Using Single $4:1$ MUX [3 Marks]}
Let select lines be $S_1 = A, S_0 = B$:
\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline
\textbf{Select Inputs} $(A, B)$ & \textbf{Minterms Included} & \textbf{Function Output $Y$} & \textbf{Data Input Line} \\ \hline
$00$ & $m_0(\bar{C}) + m_1(C) \to m_0$ & $\bar{C}$ & $\mathbf{I_0 = \bar{C}}$ \\ \hline
$01$ & $m_2(\bar{C}) + m_3(C) \to m_2, m_3$ & $\bar{C} + C = 1$ & $\mathbf{I_1 = 1\ (V_{CC})}$ \\ \hline
$10$ & $m_4(\bar{C}) + m_5(C) \to m_5$ & $C$ & $\mathbf{I_2 = C}$ \\ \hline
$11$ & $m_6(\bar{C}) + m_7(C) \to m_7$ & $C$ & $\mathbf{I_3 = C}$ \\ \hline
\end{tabular}
\end{center}

\begin{schematicbox}{4:1 Multiplexer Realization for $Y(A,B,C) = \sum m(0,2,3,5,7)$}
\centering
\begin{tikzpicture}[scale=0.92, transform shape]
  % 4:1 MUX Box
  \draw[thick, fill=boxbg] (3.0, 0) rectangle (6.5, 4.8);
  \node at (4.75, 4.3) {\textbf{4:1 MUX}};
  \node[anchor=west] at (3.2, 3.5) {\small $I_0$};
  \node[anchor=west] at (3.2, 2.7) {\small $I_1$};
  \node[anchor=west] at (3.2, 1.9) {\small $I_2$};
  \node[anchor=west] at (3.2, 1.1) {\small $I_3$};
  \node[anchor=north] at (4.0, 0) {\small $S_1$};
  \node[anchor=north] at (5.5, 0) {\small $S_0$};

  \draw[thick] (6.5, 2.3) -- ++(1.2, 0) node[right] {\large $\mathbf{Y}$};

  % NOT Gate for C_bar
  \draw[thick] (-0.5, 3.5) node[left] {$\mathbf{C}$} -- (0.8, 3.5);
  \node[not gate US, draw, scale=0.8] (notC) at (1.4, 3.5) {};
  \draw[thick] (0.8, 3.5) -- (notC.input);
  \draw[thick] (notC.output) -- (3.0, 3.5);

  \draw[thick] (0.5, 2.7) node[left] {$\mathbf{1\ (V_{CC})}$} -- (3.0, 2.7);
  \draw[thick] (0.8, 3.5) -- (0.8, 1.9) -- (3.0, 1.9);
  \draw[thick] (0.8, 1.9) -- (0.8, 1.1) -- (3.0, 1.1);

  % Select Inputs A, B
  \draw[thick] (1.0, -1.0) node[left] {$\mathbf{A}$} -- (4.0, -1.0) -- (4.0, 0);
  \draw[thick] (1.0, -1.6) node[left] {$\mathbf{B}$} -- (5.5, -1.6) -- (5.5, 0);
\end{tikzpicture}
\end{schematicbox}

\paragraph{Part (b): Combined Half-Adder and Half-Subtractor in a Single Circuit [7 Marks]}
Let $A$ and $B$ be the two 1-bit binary inputs, and let $M$ be the mode control line:
\begin{itemize}
  \item \textbf{Mode $M = 0$ (Half-Adder):}
  \[
  \text{Sum } S = A \oplus B, \qquad \text{Carry } C = A \cdot B
  \]
  \item \textbf{Mode $M = 1$ (Half-Subtractor):}
  \[
  \text{Difference } D = A \oplus B, \qquad \text{Borrow } B_{\text{out}} = \bar{A} \cdot B
  \]
\end{itemize}
\textbf{Key Insight:} The first output is identical in both operations: $\mathbf{\text{Sum} / \text{Difference} = A \oplus B}$.\\
The second output ($\text{Carry} / \text{Borrow}$) requires $A \cdot B$ when $M=0$ and $\bar{A} \cdot B$ when $M=1$. Using an XOR gate with mode control $M$:
\[
(A \oplus M) = \begin{cases} A \oplus 0 = A & \text{when } M = 0 \\ A \oplus 1 = \bar{A} & \text{when } M = 1 \end{cases}
\]
Therefore, the combined Carry / Borrow output equation is:
\[
\mathbf{\text{Carry} / \text{Borrow} = (A \oplus M) \cdot B}
\]

\begin{schematicbox}{Combined Half-Adder and Half-Subtractor Circuit Schematic}
\centering
\begin{tikzpicture}[scale=0.95, transform shape]
  % XOR 1 for Sum / Difference
  \node[xor gate US, draw, logic gate inputs=nn, scale=1.1] (xorSum) at (4.5, 3.2) {};
  \draw[thick] (0.5, 3.45) node[left] {\large $\mathbf{A}$} -- (xorSum.input 1);
  \draw[thick] (0.5, 2.95) node[left] {\large $\mathbf{B}$} -- (xorSum.input 2);
  \draw[thick] (xorSum.output) -- ++(1.8, 0) node[right] {\large $\mathbf{\text{Sum} / \text{Difference} = A \oplus B}$};

  % XOR 2 for Mode Control (A XOR M)
  \node[xor gate US, draw, logic gate inputs=nn, scale=1.0] (xorM) at (3.5, 1.2) {};
  \draw[thick] (1.8, 3.45) |- (xorM.input 1);
  \draw[thick] (0.5, 0.95) node[left] {\large $\mathbf{M\ (\text{Mode})}$} -- (xorM.input 2);

  % AND Gate for Carry / Borrow
  \node[and gate US, draw, logic gate inputs=nn, scale=1.1] (andCB) at (6.0, 1.0) {};
  \draw[thick] (xorM.output) -- (andCB.input 1);
  \draw[thick] (2.2, 2.95) -- (2.2, 0.75) -- (andCB.input 2);
  \draw[thick] (andCB.output) -- ++(1.2, 0) node[right] {\large $\mathbf{\text{Carry} / \text{Borrow} = (A \oplus M)B}$};
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
\textbf{4:1 MUX Inputs:} $I_0 = \bar{C}, I_1 = 1, I_2 = C, I_3 = C$ with $S_1 = A, S_0 = B$.\\
\textbf{Combined Adder/Subtractor Equations:}
$$\mathbf{\text{Sum} / \text{Difference} = A \oplus B, \qquad \text{Carry} / \text{Borrow} = (A \oplus M) \cdot B}$$
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 5
% =========================================================================
\subsection{Question 5: Mod-6 Synchronous DOWN Counter Schematic [7 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q5)}
Design a mod-6 synchronous down counter using JK flip-flops.
\end{questionbox}

A \textbf{Mod-6 Synchronous DOWN Counter} counts backward through 6 states:
\[
5 \to 4 \to 3 \to 2 \to 1 \to 0 \to 5 \quad (101_2 \to 100_2 \to 011_2 \to 010_2 \to 001_2 \to 000_2 \to 101_2)
\]
Requires $N = 3$ flip-flops ($Q_2, Q_1, Q_0$). Unused states: $110_2$ and $111_2$ (treated as Don't Cares).

\paragraph{1. State Transition and JK Excitation Table:}
\begin{center}
\begin{tabular}{|c|ccc|ccc|cccccc|}
\hline
\textbf{State} & \multicolumn{3}{c|}{\textbf{Present State}} & \multicolumn{3}{c|}{\textbf{Next State}} & \multicolumn{6}{c|}{\textbf{JK Flip-Flop Inputs}} \\
& $Q_2$ & $Q_1$ & $Q_0$ & $Q_2^+$ & $Q_1^+$ & $Q_0^+$ & $\mathbf{J_2}$ & $\mathbf{K_2}$ & $\mathbf{J_1}$ & $\mathbf{K_1}$ & $\mathbf{J_0}$ & $\mathbf{K_0}$ \\ \hline
5 & 1 & 0 & 1 & 1 & 0 & 0 & $X$ & 0 & 0 & $X$ & $X$ & 1 \\ \hline
4 & 1 & 0 & 0 & 0 & 1 & 1 & $X$ & 1 & 1 & $X$ & 1 & $X$ \\ \hline
3 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & $X$ & $X$ & 0 & $X$ & 1 \\ \hline
2 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & $X$ & $X$ & 1 & 1 & $X$ \\ \hline
1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & $X$ & 0 & $X$ & $X$ & 1 \\ \hline
0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 & $X$ & 0 & $X$ & 1 & $X$ \\ \hline
\end{tabular}
\end{center}

\paragraph{2. Minimized JK Equations via K-Maps:}
\begin{itemize}
  \item $\mathbf{J_0 = 1, \qquad K_0 = 1}$ (LSB toggles every single clock edge).
  \item $\mathbf{J_1 = \bar{Q}_2 \bar{Q}_0, \qquad K_1 = \bar{Q}_0}$.
  \item $\mathbf{J_2 = \bar{Q}_1 \bar{Q}_0, \qquad K_2 = \bar{Q}_1 \bar{Q}_0}$ (or $K_2 = \bar{Q}_0$).
\end{itemize}

\paragraph{3. Lock-out and Self-Starting Verification:}
\begin{itemize}
  \item If counter powers up in state $110_2$: $Q_2^+=1, Q_1^+=0, Q_0^+=1 \implies \text{Next State } 101_2$ (Valid state!).
  \item If counter powers up in state $111_2$: $Q_2^+=1, Q_1^+=1, Q_0^+=0 \implies \text{Next State } 110_2 \to 101_2$ (Valid state!).
\end{itemize}

\begin{schematicbox}{Mod-6 Synchronous DOWN Counter Logic Circuit}
\centering
\begin{tikzpicture}[scale=0.70, transform shape]
  % 3 JK Flip Flops (Width 2.0 each, wide 3.6cm inter-stage gaps)
  % FF0: x in [0, 2.0]
  % FF1: x in [5.6, 7.6]
  % FF2: x in [11.2, 13.2]
  \foreach \i/\xpos in {0/0, 1/5.6, 2/11.2} {
    \draw[thick, fill=boxbg] (\xpos, 0) rectangle (\xpos + 2.0, 3.6);
    \node at (\xpos + 1.0, 3.1) {\textbf{FF\i\ (JK)}};
    \node[anchor=west] at (\xpos + 0.2, 2.4) {\small $J$};
    \node[anchor=west] at (\xpos + 0.2, 1.6) {\small $>$};
    \node[anchor=west] at (\xpos + 0.2, 0.8) {\small $K$};
    \node[anchor=east] at (\xpos + 1.8, 2.4) {\small $Q_\i$};
    \node[anchor=east] at (\xpos + 1.8, 0.8) {\small $\bar{Q}_\i$};

    \filldraw[black] (\xpos + 2.4, 2.4) circle (2pt);
    \draw[thick] (\xpos + 2.0, 2.4) -- (\xpos + 2.4, 2.4) -- (\xpos + 2.4, 4.4) node[above] {\large $\mathbf{Q_\i}$};
  }

  % J0 = K0 = 1 (VCC)
  \draw[thick] (-1.0, 2.4) node[left] {\large $\mathbf{1\ (V_{CC})}$} -- (0, 2.4);
  \draw[thick] (-0.4, 2.4) |- (0, 0.8);

  % Common Synchronous Clock Rail
  \draw[thick] (-1.0, -1.0) node[left] {\large $\mathbf{\text{CLK}}$} -- (12.5, -1.0);
  \foreach \xpos in {0, 5.6, 11.2} {
    \draw[thick] (\xpos + 0.5, -1.0) -- (\xpos + 0.5, 1.6) -- (\xpos + 0.2, 1.6);
  }

  % AND Gate for J1 = Q2_bar . Q0_bar (in gap [2.0, 5.6])
  \node[and gate US, draw, logic gate inputs=nn] (andJ1) at (4.6, 2.4) {};
  \draw[thick] (3.6, 2.55) node[left] {\footnotesize $\bar{Q}_2$} -- (andJ1.input 1);
  \draw[thick] (3.6, 2.25) node[left] {\footnotesize $\bar{Q}_0$} -- (andJ1.input 2);
  \draw[thick] (andJ1.output) -- (5.6, 2.4);

  % K1 = Q0_bar
  \draw[thick] (2.0, 0.8) -- (2.6, 0.8) -- (2.6, 0.8) |- (5.6, 0.8);

  % AND Gate for J2 = K2 = Q1_bar . Q0_bar (in gap [7.6, 11.2])
  \node[and gate US, draw, logic gate inputs=nn] (and2) at (10.2, 1.6) {};
  \draw[thick] (9.2, 1.75) node[left] {\footnotesize $\bar{Q}_1$} -- (and2.input 1);
  \draw[thick] (9.2, 1.45) node[left] {\footnotesize $\bar{Q}_0$} -- (and2.input 2);
  \draw[thick] (and2.output) -- (10.8, 1.6) |- (11.2, 2.4);
  \draw[thick] (10.8, 1.6) |- (11.2, 0.8);
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
$$\mathbf{J_0 = 1, \ K_0 = 1, \quad J_1 = \bar{Q}_2\bar{Q}_0, \ K_1 = \bar{Q}_0, \quad J_2 = K_2 = \bar{Q}_1\bar{Q}_0}$$
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 7
% =========================================================================
\subsection{Question 7: 4-Bit SIPO Shift Register Schematic \& Waveforms [5 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q7)}
Explain the working of 4-bit SIPO shift register with timing diagram for data input `1011'.
\end{questionbox}

\paragraph{1. Circuit Configuration:}
\begin{itemize}
  \item 4 D flip-flops cascaded in series ($D_{\text{in}} \to D_3, Q_3 \to D_2, Q_2 \to D_1, Q_1 \to D_0$).
  \item Common clock shifts data one stage right on each positive clock edge.
  \item Parallel outputs $Q_3, Q_2, Q_1, Q_0$ available simultaneously after 4 pulses.
\end{itemize}

\begin{schematicbox}{4-Bit SIPO Shift Register Circuit Schematic}
\centering
\begin{tikzpicture}[scale=0.88, transform shape]
  % 4 D Flip-Flops
  \foreach \i/\ffname in {3/FF3 ($Q_3$), 2/FF2 ($Q_2$), 1/FF1 ($Q_1$), 0/FF0 ($Q_0$)} {
    \draw[thick, fill=boxbg] ({3.6*(3 - \i)}, 0) rectangle ({3.6*(3 - \i) + 2.4}, 3.2);
    \node at ({3.6*(3 - \i) + 1.2}, 2.7) {\textbf{\ffname}};
    \node[anchor=west] at ({3.6*(3 - \i) + 0.2}, 1.8) {\small $D$};
    \node[anchor=west] at ({3.6*(3 - \i) + 0.2}, 0.8) {\small $>$};
    \node[anchor=east] at ({3.6*(3 - \i) + 2.2}, 1.8) {\small $Q$};
    
    % Parallel output taps
    \filldraw[black] ({3.6*(3 - \i) + 2.8}, 1.8) circle (2pt);
    \draw[thick] ({3.6*(3 - \i) + 2.8}, 1.8) -- ({3.6*(3 - \i) + 2.8}, 4.2) node[above] {\large $\mathbf{Q_\i}$};
  }

  % Serial Input to FF3
  \draw[thick] (-1.5, 1.8) node[left] {\large $\mathbf{D_{\text{in}}\ (\text{Serial In})}$} -- (0, 1.8);

  % Inter-stage connections
  \draw[thick] (2.4, 1.8) -- (3.6, 1.8);
  \draw[thick] (6.0, 1.8) -- (7.2, 1.8);
  \draw[thick] (9.6, 1.8) -- (10.8, 1.8);
  \draw[thick] (13.2, 1.8) -- (13.6, 1.8);

  % Common Clock Rail
  \draw[thick] (-1.5, -0.8) node[left] {\large $\mathbf{\text{CLK}}$} -- (12.0, -0.8);
  \foreach \i in {0,1,2,3} {
    \draw[thick] ({3.6*\i + 0.4}, -0.8) -- ({3.6*\i + 0.4}, 0.8) -- ({3.6*\i + 0.2}, 0.8);
  }
\end{tikzpicture}
\end{schematicbox}

\paragraph{2. Shift Sequence Table for $1011_2$ (MSB entered first):}
Assume initial contents $Q_3 Q_2 Q_1 Q_0 = 0000_2$.
\begin{center}
\begin{tabular}{|c|c|cccc|l|}
\hline
\textbf{Clock Pulse} & \textbf{Serial Input ($D_{\text{in}}$)} & $\mathbf{Q_3}$ & $\mathbf{Q_2}$ & $\mathbf{Q_1}$ & $\mathbf{Q_0}$ & \textbf{State Summary} \\ \hline
\textbf{Initial} & $-$ & 0 & 0 & 0 & 0 & Cleared state \\ \hline
\textbf{CLK 1} & $1$ (MSB) & 1 & 0 & 0 & 0 & First bit into FF3 \\ \hline
\textbf{CLK 2} & $0$ & 0 & 1 & 0 & 0 & Shift right, second bit in \\ \hline
\textbf{CLK 3} & $1$ & 1 & 0 & 1 & 0 & Shift right, third bit in \\ \hline
\textbf{CLK 4} & $1$ (LSB) & 1 & 1 & 0 & 1 & Complete word loaded ($1011_2$) \\ \hline
\end{tabular}
\end{center}

\begin{schematicbox}{Timing Waveforms for Shifting $1011_2$ into SIPO Register}
\centering
\begin{tikzpicture}[scale=0.9, transform shape]
  % Vertical grid lines
  \foreach \x in {0, 2.5, 5.0, 7.5, 10.0, 12.5} {
    \draw[dotted, gray!60] (\x, 1.2) -- (\x, -6.5);
  }
  
  % Clock Waveform
  \node[left] at (-0.3, 0.5) {\textbf{CLK}};
  \draw[thick, blue] (0,0) -- (1.25,0) -- (1.25,1) -- (2.5,1) -- (2.5,0) -- (3.75,0) -- (3.75,1) -- (5.0,1) -- (5.0,0) -- (6.25,0) -- (6.25,1) -- (7.5,1) -- (7.5,0) -- (8.75,0) -- (8.75,1) -- (10.0,1) -- (10.0,0) -- (11.25,0) -- (11.25,1) -- (12.5,1);
  \node at (1.87, 1.3) {\small Pulse 1};
  \node at (4.37, 1.3) {\small Pulse 2};
  \node at (6.87, 1.3) {\small Pulse 3};
  \node at (9.37, 1.3) {\small Pulse 4};

  % Serial In (1, 0, 1, 1)
  \node[left] at (-0.3, -0.8) {\textbf{$D_{\text{in}}$}};
  \draw[thick, red] (0, -0.3) -- (2.5, -0.3) -- (2.5, -1.3) -- (5.0, -1.3) -- (5.0, -0.3) -- (10.0, -0.3) -- (10.0, -1.3) -- (12.5, -1.3);
  \node at (1.25, -0.1) {\small '1'}; \node at (3.75, -1.5) {\small '0'}; \node at (6.25, -0.1) {\small '1'}; \node at (8.75, -0.1) {\small '1'};

  % Q3
  \node[left] at (-0.3, -2.3) {\textbf{$Q_3$}};
  \draw[thick, teal] (0, -2.8) -- (2.5, -2.8) -- (2.5, -1.8) -- (5.0, -1.8) -- (5.0, -2.8) -- (7.5, -2.8) -- (7.5, -1.8) -- (12.5, -1.8);
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
Parallel output after 4 clock pulses is $\mathbf{Q_3 Q_2 Q_1 Q_0 = 1101_2}$ (corresponding to serial arrival sequence $1011_2$).
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 8
% =========================================================================
\subsection{Question 8: 3-Bit Asynchronous UP/DOWN Counter Schematic [5 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q8)}
Explain the operation of 3-bit asynchronous up/down counter with logic diagram.
\end{questionbox}

An asynchronous UP/DOWN counter uses a control line $M$ to steer either the normal output $Q$ (for DOWN counting with negative-edge clocking) or inverted output $\bar{Q}$ (for UP counting with negative-edge clocking) to the clock input of the next stage:
\[
\text{CLK}_{i+1} = \bar{M} Q_i + M \bar{Q}_i = M \oplus Q_i
\]

\begin{schematicbox}{3-Bit Negative-Edge Triggered Asynchronous UP/DOWN Counter}
\centering
\begin{tikzpicture}[scale=0.88, transform shape]
  % 3 T Flip Flops
  \foreach \i in {0,1,2} {
    \draw[thick, fill=boxbg] ({4.4*\i}, 0) rectangle ({4.4*\i + 2.6}, 3.4);
    \node at ({4.4*\i + 1.3}, 2.9) {\textbf{FF\i\ (T)}};
    \node[anchor=west] at ({4.4*\i + 0.2}, 2.2) {\small $T=1$};
    \node[anchor=west] at ({4.4*\i + 0.2}, 1.2) {\small $\circ>$};
    \node[anchor=east] at ({4.4*\i + 2.4}, 2.2) {\small $Q_\i$};
    \node[anchor=east] at ({4.4*\i + 2.4}, 1.2) {\small $\bar{Q}_\i$};

    \filldraw[black] ({4.4*\i + 3.0}, 2.2) circle (2pt);
    \draw[thick] ({4.4*\i + 2.6}, 2.2) -- ({4.4*\i + 3.0}, 2.2) -- ({4.4*\i + 3.0}, 4.2) node[above] {\large $\mathbf{Q_\i}$};
  }

  % External Clock to FF0
  \draw[thick] (-1.2, 1.2) node[left] {\large $\mathbf{\text{CLK}}$} -- (0, 1.2);

  % Steering Logic between FF0 and FF1
  \node[and gate US, draw, logic gate inputs=nn] (and0a) at (3.2, 2.0) {};
  \node[and gate US, draw, logic gate inputs=nn] (and0b) at (3.2, 0.8) {};
  \node[or gate US, draw, logic gate inputs=nn] (or0) at (4.0, 1.2) {};
  \draw[thick] (2.6, 2.2) -- (3.0, 2.2) |- (and0a.input 2);
  \draw[thick] (2.6, 1.2) -- (3.0, 1.2) |- (and0b.input 1);
  \draw[thick] (and0a.output) -- (or0.input 1);
  \draw[thick] (and0b.output) -- (or0.input 2);
  \draw[thick] (or0.output) -- (4.4, 1.2);

  % Steering Logic between FF1 and FF2
  \node[and gate US, draw, logic gate inputs=nn] (and1a) at (7.6, 2.0) {};
  \node[and gate US, draw, logic gate inputs=nn] (and1b) at (7.6, 0.8) {};
  \node[or gate US, draw, logic gate inputs=nn] (or1) at (8.4, 1.2) {};
  \draw[thick] (7.0, 2.2) -- (7.4, 2.2) |- (and1a.input 2);
  \draw[thick] (7.0, 1.2) -- (7.4, 1.2) |- (and1b.input 1);
  \draw[thick] (and1a.output) -- (or1.input 1);
  \draw[thick] (and1b.output) -- (or1.input 2);
  \draw[thick] (or1.output) -- (8.8, 1.2);

  % Mode Control Rails (UP = M_bar, DOWN = M)
  \draw[thick] (-1.2, 3.8) node[left] {\large $\mathbf{\overline{\text{UP}}/\text{DOWN}\ (M)}$} -- (8.0, 3.8);
  \draw[thick] (2.8, 3.8) |- (and0b.input 2);
  \draw[thick] (7.2, 3.8) |- (and1b.input 2);

  \node[not gate US, draw, scale=0.8] (notM) at (-0.2, 3.2) {};
  \draw[thick] (-0.8, 3.8) |- (notM.input);
  \draw[thick] (notM.output) -- (8.0, 3.2);
  \draw[thick] (2.8, 3.2) |- (and0a.input 1);
  \draw[thick] (7.2, 3.2) |- (and1a.input 1);
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
$$\mathbf{M=0 \implies \text{UP Counting } (Q_0 \to \text{CLK}_1, Q_1 \to \text{CLK}_2), \qquad M=1 \implies \text{DOWN Counting } (\bar{Q}_0 \to \text{CLK}_1, \bar{Q}_1 \to \text{CLK}_2)}$$
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 9
% =========================================================================
\subsection{Question 9: Synchronous FSM Sequence Detector '101' [7 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q9)}
Design a synchronous sequential machine that has 1-bit serial input $X$ and output $Z$ which will be high when the input contains the message `101' (Use SR Flip-Flop).
\end{questionbox}

\paragraph{1. State Definitions and State Transition Diagram (Mealy Model):}
\begin{itemize}
  \item $S_0 (00)$: Reset state.
  \item $S_1 (01)$: Sequence `1' detected.
  \item $S_2 (10)$: Sequence `10' detected.
  \item In $S_2$, when $X=1 \implies$ `101' detected $\implies Z=1$, next state $S_1$ (overlapping allowed).
\end{itemize}

\begin{schematicbox}{State Transition Diagram for '101' Sequence Detector}
\centering
\begin{tikzpicture}[->, >=Stealth, auto, node distance=3.2cm, thick]
  \node[state, initial] (S0) {$S_0 (00)$};
  \node[state] (S1) [right of=S0] {$S_1 (01)$};
  \node[state] (S2) [right of=S1] {$S_2 (10)$};

  \path (S0) edge [loop above] node {$X=0 / 0$} (S0)
             edge [bend left] node {$X=1 / 0$} (S1)
        (S1) edge [loop above] node {$X=1 / 0$} (S1)
             edge [bend left] node {$X=0 / 0$} (S2)
        (S2) edge [bend left] node {$X=1 / 1$} (S1)
             edge [bend left=45] node {$X=0 / 0$} (S0);
\end{tikzpicture}
\end{schematicbox}

\paragraph{2. State and Excitation Table for SR Flip-Flops ($A, B$):}
\begin{center}
\begin{tabular}{|cc|c|cc|c|cccc|}
\hline
\multicolumn{2}{|c|}{\textbf{Present State}} & \textbf{Input} & \multicolumn{2}{c|}{\textbf{Next State}} & \textbf{Output} & \multicolumn{4}{c|}{\textbf{SR Inputs}} \\
$A$ & $B$ & $X$ & $A^+$ & $B^+$ & $\mathbf{Z}$ & $\mathbf{S_A}$ & $\mathbf{R_A}$ & $\mathbf{S_B}$ & $\mathbf{R_B}$ \\ \hline
0 & 0 & 0 & 0 & 0 & 0 & 0 & $X$ & 0 & $X$ \\ \hline
0 & 0 & 1 & 0 & 1 & 0 & 0 & $X$ & 1 & 0 \\ \hline
0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 \\ \hline
0 & 1 & 1 & 0 & 1 & 0 & 0 & $X$ & $X$ & 0 \\ \hline
1 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & $X$ \\ \hline
1 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 1 & 0 \\ \hline
1 & 1 & 0 & $X$ & $X$ & $X$ & $X$ & $X$ & $X$ & $X$ \\ \hline
1 & 1 & 1 & $X$ & $X$ & $X$ & $X$ & $X$ & $X$ & $X$ \\ \hline
\end{tabular}
\end{center}

\paragraph{3. Minimized Equations via K-Maps:}
\begin{align*}
S_A &= B\bar{X} \\
R_A &= X + \bar{B} \\
S_B &= \bar{A}X \\
R_B &= \bar{X} \\
Z &= AX
\end{align*}

\begin{schematicbox}{Complete Synchronous Logic Schematic Using SR Flip-Flops}
\centering
\begin{tikzpicture}[scale=0.88, transform shape]
  % 2 SR Flip Flops
  \draw[thick, fill=boxbg] (2.2, 0) rectangle (4.8, 3.6);
  \node at (3.5, 3.1) {\textbf{FF-A (SR)}};
  \node[anchor=west] at (2.4, 2.4) {\small $S_A$};
  \node[anchor=west] at (2.4, 1.6) {\small $>$};
  \node[anchor=west] at (2.4, 0.8) {\small $R_A$};
  \node[anchor=east] at (4.6, 2.4) {\small $A$};
  \node[anchor=east] at (4.6, 0.8) {\small $\bar{A}$};

  \draw[thick, fill=boxbg] (8.0, 0) rectangle (10.6, 3.6);
  \node at (9.3, 3.1) {\textbf{FF-B (SR)}};
  \node[anchor=west] at (8.2, 2.4) {\small $S_B$};
  \node[anchor=west] at (8.2, 1.6) {\small $>$};
  \node[anchor=west] at (8.2, 0.8) {\small $R_B$};
  \node[anchor=east] at (10.4, 2.4) {\small $B$};
  \node[anchor=east] at (10.4, 0.8) {\small $\bar{B}$};

  % Clock
  \draw[thick] (-1.5, -0.8) node[left] {\large $\mathbf{\text{CLK}}$} -- (9.5, -0.8);
  \draw[thick] (3.0, -0.8) -- (3.0, 1.6) -- (2.4, 1.6);
  \draw[thick] (8.8, -0.8) -- (8.8, 1.6) -- (8.2, 1.6);

  % Combinational Gates for FF-A:
  % S_A = B . X_bar
  \node[and gate US, draw, logic gate inputs=nn] (andSA) at (0.8, 2.4) {};
  \draw[thick] (0, 2.55) node[left] {\footnotesize $B$} -- (andSA.input 1);
  \draw[thick] (0, 2.25) node[left] {\footnotesize $\bar{X}$} -- (andSA.input 2);
  \draw[thick] (andSA.output) -- (2.2, 2.4);

  % R_A = X + B_bar
  \node[or gate US, draw, logic gate inputs=nn] (orRA) at (0.8, 0.8) {};
  \draw[thick] (0, 0.95) node[left] {\footnotesize $X$} -- (orRA.input 1);
  \draw[thick] (0, 0.65) node[left] {\footnotesize $\bar{B}$} -- (orRA.input 2);
  \draw[thick] (orRA.output) -- (2.2, 0.8);

  % Combinational Gates for FF-B:
  % S_B = A_bar . X
  \node[and gate US, draw, logic gate inputs=nn] (andSB) at (6.6, 2.4) {};
  \draw[thick] (5.8, 2.55) node[left] {\footnotesize $\bar{A}$} -- (andSB.input 1);
  \draw[thick] (5.8, 2.25) node[left] {\footnotesize $X$} -- (andSB.input 2);
  \draw[thick] (andSB.output) -- (8.0, 2.4);

  % R_B = X_bar
  \draw[thick] (6.0, 0.8) node[left] {\footnotesize $\bar{X}$} -- (8.0, 0.8);

  % Output Z = A . X
  \node[and gate US, draw, logic gate inputs=nn] (andZ) at (12.6, 2.4) {};
  \draw[thick] (4.8, 2.4) -- (5.4, 2.4) -- (5.4, 4.4) -- (11.8, 4.4) |- (andZ.input 1);
  \draw[thick] (11.0, 1.6) node[left] {$X$} -- (andZ.input 2);
  \draw[thick] (andZ.output) -- ++(1.0, 0) node[right] {\large $\mathbf{Z}$};
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
$$\mathbf{S_A = B\bar{X}, \quad R_A = X + \bar{B}, \quad S_B = \bar{A}X, \quad R_B = \bar{X}, \quad Z = AX}$$
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 9
% =========================================================================
\subsection{Question 9: Two-Input TTL NOR Gate Transistor Circuit [5 + 2 = 7 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q9)}
Draw the circuit diagram of two-input TTL NOR gate and explain its logic operation briefly and list the characteristics of CMOS logic family.
\end{questionbox}

\paragraph{Part (a): 2-Input TTL NOR Gate Transistor Circuit \& Operation [5 Marks]}
A Transistor-Transistor Logic (TTL) NOR gate uses:
\begin{itemize}
  \item \textbf{Dual Input Stages (Parallel branches):}
  \begin{itemize}
    \item Input $A$ drives input transistor $Q_1$ (with pull-up $R_1 = 4\text{k}\Omega$) which controls phase-splitter $Q_3$.
    \item Input $B$ drives input transistor $Q_2$ (with pull-up $R_2 = 4\text{k}\Omega$) which controls phase-splitter $Q_4$.
  \end{itemize}
  \item \textbf{Parallel Phase Splitters ($Q_3 \parallel Q_4$):}
  $Q_3$ and $Q_4$ share a common collector load ($R_3 = 1.6\text{k}\Omega$) and a common emitter resistor ($R_4 = 1\text{k}\Omega$).
  \item \textbf{Output Totem-Pole Stage:}
  Upper active pull-up transistor $Q_5$ with series diode $D_1$ and current-limiting resistor $R_5 = 130\Omega$, and lower pull-down transistor $Q_6$.
\end{itemize}

\begin{schematicbox}{Transistor Schematic of 2-Input Standard TTL NOR Gate}
\centering
\begin{tikzpicture}[scale=0.9, transform shape]
  % VCC Rail
  \draw[thick] (0, 7.5) -- (12.5, 7.5);
  \node[above] at (6.25, 7.5) {\large $\mathbf{V_{CC} = +5.0\text{V}}$};

  % TOP BRANCH: Input A -> Q1 -> Q3
  % R1
  \draw[thick] (1.5, 7.5) -- (1.5, 6.4) node[draw, fill=boxbg, minimum width=0.6cm, minimum height=0.7cm] (r1) {\small $4\text{k}\Omega$};
  \draw[thick] (r1.south) -- (1.5, 5.0);
  % Q1
  \draw[thick, fill=boxbg] (1.0, 4.2) rectangle (2.0, 5.0); \node at (1.5, 4.6) {\small $\mathbf{Q_1}$};
  \draw[thick] (0.0, 4.6) node[left] {\large $\mathbf{A}$} -- (1.0, 4.6);
  % Q3
  \draw[thick, fill=boxbg] (4.0, 4.2) rectangle (5.0, 5.0); \node at (4.5, 4.6) {\small $\mathbf{Q_3}$};
  \draw[thick] (2.0, 4.6) -- (4.0, 4.6); % Q1 coll to Q3 base

  % BOTTOM BRANCH: Input B -> Q2 -> Q4
  % R2
  \draw[thick] (1.5, 3.5) -- (1.5, 2.7) node[draw, fill=boxbg, minimum width=0.6cm, minimum height=0.7cm] (r2) {\small $4\text{k}\Omega$};
  \draw[thick] (1.5, 7.5) -| (0.6, 3.5) -- (1.5, 3.5);
  \draw[thick] (r2.south) -- (1.5, 1.8);
  % Q2
  \draw[thick, fill=boxbg] (1.0, 1.0) rectangle (2.0, 1.8); \node at (1.5, 1.4) {\small $\mathbf{Q_2}$};
  \draw[thick] (0.0, 1.4) node[left] {\large $\mathbf{B}$} -- (1.0, 1.4);
  % Q4
  \draw[thick, fill=boxbg] (4.0, 1.0) rectangle (5.0, 1.8); \node at (4.5, 1.4) {\small $\mathbf{Q_4}$};
  \draw[thick] (2.0, 1.4) -- (4.0, 1.4); % Q2 coll to Q4 base

  % Common Phase Splitter Collector Load R3
  \draw[thick] (6.2, 7.5) -- (6.2, 6.4) node[draw, fill=boxbg, minimum width=0.6cm, minimum height=0.7cm] (r3) {\small $1.6\text{k}\Omega$};
  \draw[thick] (r3.south) -- (6.2, 4.6);
  \draw[thick] (5.0, 4.6) -- (6.2, 4.6);
  \draw[thick] (5.0, 1.4) -- (6.2, 1.4) -- (6.2, 4.6);

  % Common Phase Splitter Emitter to Q6 Base and R4
  \draw[thick] (4.5, 4.2) -- (4.5, 3.0) -- (7.5, 3.0);
  \draw[thick] (4.5, 1.0) -- (4.5, 0.4) -- (7.5, 0.4) |- (7.5, 3.0);

  % Totem Pole Stage: Q5, D1, Q6
  % R5
  \draw[thick] (10.0, 7.5) -- (10.0, 6.6) node[draw, fill=boxbg, minimum width=0.6cm, minimum height=0.6cm] (r5) {\small $130\Omega$};
  \draw[thick] (r5.south) -- (10.0, 5.6);
  % Q5
  \draw[thick, fill=boxbg] (9.5, 4.8) rectangle (10.5, 5.6); \node at (10.0, 5.2) {\small $\mathbf{Q_5}$};
  \draw[thick] (6.2, 4.6) -- (9.5, 5.2); % Base of Q5

  % D1
  \draw[thick] (10.0, 4.8) -- (10.0, 4.2) node[draw, fill=boxbg, minimum width=0.6cm, minimum height=0.4cm] (d1) {\small $\mathbf{D_1}$};
  \draw[thick] (d1.south) -- (10.0, 3.2);

  % Q6
  \draw[thick, fill=boxbg] (9.5, 1.8) rectangle (10.5, 2.6); \node at (10.0, 2.2) {\small $\mathbf{Q_6}$};
  \draw[thick] (7.5, 3.0) |- (9.5, 2.2); % Base of Q6 from phase splitters
  \draw[thick] (10.0, 3.2) -- (10.0, 2.6);

  % Output node Y
  \draw[thick] (10.0, 3.2) -- (12.2, 3.2) node[right] {\large $\mathbf{Y = \overline{A + B}}$};

  % Ground
  \draw[thick] (10.0, 1.8) -- (10.0, 0.8);
  \draw[thick] (9.4, 0.8) -- (10.6, 0.8);
  \draw[thick] (9.6, 0.6) -- (10.4, 0.6);
  \draw[thick] (9.8, 0.4) -- (10.2, 0.4);
  \node[below] at (10.0, 0.4) {\textbf{GND}};
\end{tikzpicture}
\end{schematicbox}

\paragraph{Logic Operation Table:}
\begin{center}
\begin{tabular}{|cc||cc|cc|cc||c|l|}
\hline
$\mathbf{A}$ & $\mathbf{B}$ & $\mathbf{Q_1}$ & $\mathbf{Q_2}$ & $\mathbf{Q_3}$ & $\mathbf{Q_4}$ & $\mathbf{Q_5}$ & $\mathbf{Q_6}$ & $\mathbf{Y}$ & \textbf{Logic State} \\ \hline
0 & 0 & Sat & Sat & OFF & OFF & ON & OFF & $\mathbf{1}\ (\approx 3.4\text{V})$ & High Output ($V_{OH}$) \\ \hline
0 & 1 & Sat & Inv & OFF & ON & OFF & ON & $\mathbf{0}\ (\approx 0.2\text{V})$ & Low Output ($V_{OL}$) \\ \hline
1 & 0 & Inv & Sat & ON & OFF & OFF & ON & $\mathbf{0}\ (\approx 0.2\text{V})$ & Low Output ($V_{OL}$) \\ \hline
1 & 1 & Inv & Inv & ON & ON & OFF & ON & $\mathbf{0}\ (\approx 0.2\text{V})$ & Low Output ($V_{OL}$) \\ \hline
\end{tabular}
\end{center}

\paragraph{Part (b): Characteristics of CMOS Logic Family [2 Marks]}
\begin{enumerate}
  \item \textbf{Extremely Low Static Power Consumption:} Near zero ($< 10\text{ nW}$ per gate), power is consumed only during switching transitions.
  \item \textbf{Wide Supply Voltage Range:} Operates reliably from $+3\text{V}$ to $+15\text{V}$ (4000 series) or $+2\text{V}$ to $+6\text{V}$ (74HC series).
  \item \textbf{Very High Noise Immunity:} Noise margin is typically $40\%$ to $45\%$ of $V_{DD}$ ($> 1.5\text{V}$ at $V_{DD}=5\text{V}$).
  \item \textbf{Extremely High Fan-Out:} Fan-out $> 50$ due to nearly infinite MOSFET input resistance ($R_{\text{in}} > 10^{12}\ \Omega$).
  \item \textbf{Full Rail-to-Rail Output Swing:} $V_{OH} \approx V_{DD}$ and $V_{OL} \approx 0\text{V}$.
\end{enumerate}

\begin{answerbox}
The TTL NOR gate uses parallel phase splitters ($Q_3, Q_4$) to pull the totem-pole output LOW whenever either input is HIGH. CMOS logic provides near-zero static power dissipation and high noise margins.
\end{answerbox}

\vspace{0.6cm}

% =========================================================================
% QUESTION 10
% =========================================================================
\subsection{Question 10: Digital Frequency Measurement Block Diagram [4 Marks]}
\begin{questionbox}{Problem Statement (2081 Ashwin, Q10)}
With the help of functional diagram explain the operation of frequency measurement.
\end{questionbox}

A \textbf{Digital Frequency Measurement System} determines the unknown frequency $f_x$ of an input waveform by accumulating the count of input cycles during a calibrated time gate interval $T_{\text{gate}}$:
\[
f_x = \frac{N}{T_{\text{gate}}}
\]

\paragraph{Operational Principle:}
\begin{enumerate}
  \item \textbf{Input Waveform Conditioning:} The unknown periodic analog signal is amplified and passed through a \textbf{Schmitt Trigger}, converting it into a clean train of digital clock pulses of frequency $f_x$.
  \item \textbf{Time Base Generation:} A high-precision crystal oscillator (e.g. 1 MHz, stability $\pm 1\text{ ppm}$) feeds a chain of decade frequency dividers to synthesize accurate gate open times $T_{\text{gate}} = 1\text{ s}, 0.1\text{ s}, 10\text{ ms}$.
  \item \textbf{Gating Logic:} The Main AND Gate is enabled by the gate control bistable multivibrator for exactly $T_{\text{gate}}$. Exactly $N = f_x \times T_{\text{gate}}$ pulses pass through the gate.
  \item \textbf{Decade Counting \& Readout:} The cascaded BCD counter counts $N$ pulses, transfers the result to a latch register, and illuminates the 7-segment digital display.
\end{enumerate}

\begin{schematicbox}{Block Diagram of Digital Frequency Measurement System}
\centering
\begin{tikzpicture}[scale=0.88, transform shape, >=Stealth]
  % Input channel
  \node[draw, thick, fill=boxbg, minimum width=2.2cm, minimum height=1.2cm, align=center] (amp) at (0, 3) {Input Attenuator\\\& Amplifier};
  \node[draw, thick, fill=boxbg, minimum width=2.2cm, minimum height=1.2cm, align=center] (schmitt) at (3.4, 3) {Schmitt Trigger\\(Wave Shaper)};
  \node[draw, thick, fill=boxbg, minimum width=1.8cm, minimum height=1.2cm, align=center] (gate) at (6.8, 3) {Main AND\\Gate};
  \node[draw, thick, fill=boxbg, minimum width=2.4cm, minimum height=1.2cm, align=center] (count) at (10.2, 3) {Decade Counter\\Assembly};
  \node[draw, thick, fill=boxbg, minimum width=2.2cm, minimum height=1.2cm, align=center] (disp) at (13.6, 3) {Latch \& Digital\\Display};

  \draw[thick, ->] (-2.2, 3) node[left] {Input $f_x$} -- (amp.west);
  \draw[thick, ->] (amp.east) -- (schmitt.west);
  \draw[thick, ->] (schmitt.east) -- (gate.west);
  \draw[thick, ->] (gate.east) -- (count.west);
  \draw[thick, ->] (count.east) -- (disp.west);

  % Time Base channel
  \node[draw, thick, fill=boxbg, minimum width=2.2cm, minimum height=1.2cm, align=center] (osc) at (0, 0) {1 MHz Crystal\\Oscillator};
  \node[draw, thick, fill=boxbg, minimum width=2.4cm, minimum height=1.2cm, align=center] (div) at (3.4, 0) {Decade Frequency\\Dividers};
  \node[draw, thick, fill=boxbg, minimum width=2.2cm, minimum height=1.2cm, align=center] (ctrl) at (6.8, 0) {Gate Flip-Flop\\Control Logic};

  \draw[thick, ->] (osc.east) -- (div.west);
  \draw[thick, ->] (div.east) -- (ctrl.west);
  \draw[thick, ->] (ctrl.north) -- (gate.south) node[midway, right] {Gate Pulse ($T_{\text{gate}}$)};
\end{tikzpicture}
\end{schematicbox}

\begin{answerbox}
Frequency is measured by counting $N$ conditioned input pulses over a precision gate window $T_{\text{gate}}$ via the formula $\mathbf{f_x = N / T_{\text{gate}}}$.
\end{answerbox}
"""
